services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - ./docker/wiremock/mappings:/home/wiremock/mappings
      - ./docker/wiremock/__files:/home/wiremock/__files
    command: --port 8080
    networks:
      - network

networks:
  network:
    driver: bridge
